# Generated by Django 5.1.2 on 2025-01-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_petowner_user_pet_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
