# Generated by Django 5.1.2 on 2025-01-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_users_poste_user_alter_appointment_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
